version: '3.7'
services:
  frontend:
    container_name: nota_keeper_frontend
    restart: always
    build: 
      context: .
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
